Add tests for PerturbedImageVisualizer class
IntelLabs/MART pull request #15
Opened 2022-12-07 21:40 UTC by lumurillo

# What does this PR do?

Added test case for the `PerturbedImageVisualizer` class.

Fixes #14

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

## Before submitting

- [ ] The title is **self-explanatory** and the description **concisely** explains the PR
- [ ] My **PR does only one thing**, instead of bundling different changes together
- [ ] I list all the **breaking changes** introduced by this pull request
- [ ] I have commented my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have run pre-commit hooks with `pre-commit run -a` command without errors

## Did you have fun?

Make sure you had fun coding 🙃

2022-12-07 21:58 UTC, mzweilin requested changes

2022-12-07 21:58 UTC, mzweilin commented on tests/test_visualizer.py
> +    assert expected_output_path.exists()
Can we also test the image content? In the previous bug in the visualizer, it did export an image, but it's the perturbation rather than x_adv.

2022-12-08 00:33 UTC, mzweilin submitted a review, later dismissed
LGTM! Thanks for adding the test.

2022-12-08 00:58 UTC, dxoigmn reviewed
I don't think `PerturbedImageVisualizer` is written correctly given that it reaches into `Adversary`. Why doesn't `on_run_end` just call `adversary` instead of reaching into the `Adversary` class? If you were to revert `01fbbefd6e4543b413b14077b4410361cf943984` would this test actually catch the bug? Why does the test care what `adversary` does? That seems weird to me.

2022-12-08 01:10 UTC, mzweilin commented
Thanks Cory. I just realized that the visualizer can be simplified by
```diff
diff --git a/mart/attack/callbacks/visualizer.py b/mart/attack/callbacks/visualizer.py
index 625054d..4a82f33 100644
--- a/mart/attack/callbacks/visualizer.py
+++ b/mart/attack/callbacks/visualizer.py
@@ -28,8 +28,7 @@ class PerturbedImageVisualizer(Callback):
             os.makedirs(self.folder)
 
     def on_run_end(self, adversary, input, target, model, **kwargs):
-        perturbation = adversary.perturber(input, target)
-        adv_input = adversary.threat_model(input, target, perturbation, **kwargs)
+        adv_input = adversary(input, target, **kwargs)
 
         for img, tgt in zip(adv_input, target):
             fname = tgt["file_name"]
```

@lumurillo  Could you please make this change and update the test accordingly?

2022-12-08 01:23 UTC, dxoigmn commented
Is it also not the case that there is already in a perturbed input in `kwargs`? I guess `Adversary` isn't a `SequentialDict` so we don't really pass `kwargs`. But then that begs the question, why is saving perturbations a thing an `Adversary` does and not just another module in `SequentialDict`?

2022-12-08 17:23 UTC, dxoigmn commented
Should there be a test for the case  when `model=None`? I actually think that exposes a bug in the logic. Shouldn't we only visualize when `model=None` @mzweilin?

2022-12-08 17:55 UTC, dxoigmn reviewed
Should there be a test for the case when `model=None`? I actually think that exposes a bug in the logic. Shouldn't we only visualize when `model=None`, @mzweilin?

2022-12-08 17:57 UTC, dxoigmn commented
Actually nevermind. `model` will never be `None` in a callback.

2022-12-08 18:00 UTC, dxoigmn requested changes
See comment.

2022-12-08 19:34 UTC, dxoigmn approved these changes
LGTM!

2022-12-08 19:49 UTC, merged