Fix multi-GPU training
IntelLabs/MART pull request #24
Opened 2022-12-13 18:24 UTC by lumurillo

# What does this PR do?

* Change the DDP trainer's strategy.
* Remove use of trainer's `gpus` property, since it is deprecated and was affecting the use of `device` property.
* Update training instructions on GPUs in the `README.md` file.

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] Train `FasterRCNN` model with `Carla` dataset using 1 GPU:
```
python -m mart experiment=ArmoryCarlaOverObjDet_TorchvisionFasterRCNN trainer=gpu fit=true
```
- [x] Train `FasterRCNN` model with `Carla` dataset on multiple GPUs:
```
python -m mart experiment=ArmoryCarlaOverObjDet_TorchvisionFasterRCNN trainer=ddp trainer.devices=2 fit=true
```

## Before submitting

- [x] The title is **self-explanatory** and the description **concisely** explains the PR
- [x] My **PR does only one thing**, instead of bundling different changes together
- [ ] I list all the **breaking changes** introduced by this pull request
- [x] I have commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have run pre-commit hooks with `pre-commit run -a` command without errors

## Did you have fun?

Make sure you had fun coding 🙃

2022-12-14 22:39 UTC, lumurillo commented
Why we need to bind `datamodel.world_size` with `trainer.devices`?

2022-12-15 01:47 UTC, mzweilin commented
> Why we need to bind `datamodel.world_size` with `trainer.devices`?

Because `batch_size` = `datamodule.ims_per_batch` / `datamodule.world_size`

https://github.com/IntelLabs/MART/blob/6184ca764c871cc098a4e822e520f476e556a971/mart/datamodules/modular.py#L59-L65

2022-12-15 01:56 UTC, dxoigmn commented
One could also bind `trainer.devices` to `datamodule.world_size`. Either way works, but ought to be the same number (assuming single-node multi-gpu training).

2022-12-16 18:32 UTC, mzweilin requested changes
Would you update the two-GPU training example along with some documentation?

2022-12-16 18:32 UTC, mzweilin commented on README.md
> +# train on multiple GPUs using Distributed Data Parallel
Could you update with the example at https://github.com/IntelLabs/MART/pull/24#issuecomment-1351889109

2023-01-05 18:16 UTC, mzweilin approved these changes
LGTM

2023-01-05 21:12 UTC, merged